M48
; DRILL file {KiCad 7.0.5} date Mon Jan 22 17:02:44 2024
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2024-01-22T17:02:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X50782Y17087
T2
X1491Y1890
X1569Y23268
X51451Y23189
X51687Y1890
T0
M30
